export function schema(dialect) {
  const id =
    dialect === "postgres"
      ? "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
      : "INTEGER PRIMARY KEY";
  const timestamp =
    dialect === "postgres"
      ? "(to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))"
      : "CURRENT_TIMESTAMP";
  return `
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users(
 id ${id}, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password TEXT NOT NULL,
 role TEXT NOT NULL DEFAULT 'player' CHECK (role IN ('player','admin')),
 created TEXT NOT NULL DEFAULT ${timestamp}
);
CREATE UNIQUE INDEX IF NOT EXISTS users_single_owner ON users(role) WHERE role='admin';
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), expires BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS sessions_expiry ON sessions(expires);
CREATE TABLE IF NOT EXISTS game_sessions(token TEXT PRIMARY KEY, user_id INTEGER UNIQUE NOT NULL REFERENCES users(id), expires BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS game_sessions_expiry ON game_sessions(expires);
CREATE TABLE IF NOT EXISTS character_appearances(user_id INTEGER PRIMARY KEY REFERENCES users(id), appearance TEXT NOT NULL, revision INTEGER NOT NULL CHECK(revision>0), updated TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS welcome_missions(
 user_id INTEGER PRIMARY KEY REFERENCES users(id),
 phase TEXT NOT NULL CHECK (phase IN ('active','completed')),
 visited INTEGER NOT NULL CHECK (visited BETWEEN 0 AND 7),
 revision INTEGER NOT NULL CHECK (revision BETWEEN 1 AND 5),
 updated TEXT NOT NULL,
 CHECK ((phase='active' AND revision=1+(visited & 1)+((visited >> 1) & 1)+((visited >> 2) & 1)) OR
        (phase='completed' AND visited=7 AND revision=5))
);
-- One generic durable mission record per account for the clan mission. The
-- existing welcome_missions table remains untouched for Aoi's first mission.
CREATE TABLE IF NOT EXISTS clan_missions(
 user_id INTEGER PRIMARY KEY REFERENCES users(id),
 mission_id TEXT NOT NULL DEFAULT 'clan_stars' CHECK (mission_id='clan_stars'),
 status TEXT NOT NULL CHECK (status IN ('NOT_STARTED','ACCEPTED','IN_PROGRESS','TIME_EXPIRED','REPORT_PENDING','COMPLETED')),
 score INTEGER CHECK (score IS NULL OR (score >= 0 AND score <= 1000000)),
 revision INTEGER NOT NULL CHECK (revision BETWEEN 0 AND 5),
 started_at BIGINT,
 reward_claimed INTEGER NOT NULL DEFAULT 0 CHECK (reward_claimed IN (0,1)),
 updated TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS player_progress(
 user_id INTEGER PRIMARY KEY REFERENCES users(id),
 idrem_gold INTEGER NOT NULL DEFAULT 0 CHECK (idrem_gold >= 0),
 level INTEGER NOT NULL DEFAULT 0 CHECK (level >= 0),
 updated TEXT NOT NULL
);
-- Global, server-authoritative secondary missions. Three durable slots are
-- shared by all players; cooldowns survive reconnects and process restarts.
CREATE TABLE IF NOT EXISTS secondary_missions(
 slot INTEGER PRIMARY KEY CHECK (slot BETWEEN 0 AND 2),
 mission_id TEXT UNIQUE NOT NULL,
 type_id TEXT NOT NULL,
 npc_id TEXT NOT NULL,
 zone TEXT NOT NULL,
 objective TEXT NOT NULL,
 progress TEXT NOT NULL DEFAULT '[]',
 status TEXT NOT NULL CHECK (status IN ('AVAILABLE','ACCEPTED','COOLDOWN')),
 accepted_by INTEGER REFERENCES users(id),
 accepted_at BIGINT,
 completed_at BIGINT,
 available_at BIGINT NOT NULL,
 revision INTEGER NOT NULL CHECK (revision >= 1),
 last_type TEXT,
 last_npc TEXT,
 last_zone TEXT,
 updated TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS secondary_missions_available ON secondary_missions(status,available_at);
CREATE TABLE IF NOT EXISTS resets(token TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS applications(
 id ${id}, user_id INTEGER UNIQUE NOT NULL REFERENCES users(id),
 character TEXT NOT NULL, discovery TEXT NOT NULL, goals TEXT NOT NULL,
 motivation TEXT NOT NULL, story TEXT NOT NULL, answers TEXT NOT NULL,
 quiz_snapshot TEXT NOT NULL, score INTEGER NOT NULL CHECK (score BETWEEN 0 AND 10),
 status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','waitlisted','rejected')),
 message TEXT NOT NULL DEFAULT '', created TEXT NOT NULL DEFAULT ${timestamp}, updated TEXT NOT NULL DEFAULT ${timestamp}
);
CREATE INDEX IF NOT EXISTS applications_status ON applications(status);
CREATE TABLE IF NOT EXISTS allocations(user_id INTEGER PRIMARY KEY REFERENCES users(id), clan TEXT NOT NULL, affinity TEXT NOT NULL, mokuton INTEGER NOT NULL CHECK (mokuton IN (0,1)), created TEXT NOT NULL DEFAULT ${timestamp});
CREATE TABLE IF NOT EXISTS mokuton_slots(position INTEGER PRIMARY KEY CHECK (position BETWEEN 0 AND 19), potential INTEGER NOT NULL CHECK (potential IN (0,1)));
CREATE TABLE IF NOT EXISTS allocation_seats(user_id INTEGER PRIMARY KEY REFERENCES allocations(user_id), position INTEGER UNIQUE NOT NULL REFERENCES mokuton_slots(position));
CREATE TABLE IF NOT EXISTS deleted_accounts(user_id INTEGER PRIMARY KEY REFERENCES users(id), deleted_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit(id ${id}, actor INTEGER REFERENCES users(id), action TEXT NOT NULL, target INTEGER, detail TEXT NOT NULL, created TEXT NOT NULL DEFAULT ${timestamp});
`;
}
